services:
  pocketbase:
    container_name: pocketbase
    image: spectado/pocketbase:0.21.1
    ports:
      - 8090:80
    volumes:
      - ./pocketbase/pb_migrations:/pb_migrations
      - ./pocketbase/pb_hooks:/pb_hooks
    command: ["--dev"]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  
  inbucket:
    image: inbucket/inbucket:3.0.3
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100

  demo:
    container_name: demo
    build:
      context: ./
      dockerfile: ./demo.Dockerfile
    ports:
      - 5173:5173
    environment:
      VITE_PB_URL: http://pocketbase
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:5173 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  cypress:
    container_name: cypress
    image: cypress/included:13.15.1
    volumes:
      - ./demo:/e2e
    working_dir: /e2e
    environment:
      CYPRESS_DEMO_URL: http://demo:5173
      CYPRESS_INBUCKET_URL: http://inbucket:9000
      CYPRESS_PB_URL: http://pocketbase
    depends_on:
      demo:
        condition: service_healthy
      pocketbase:
        condition: service_healthy

  cypress_x11:
    container_name: cypress_x11
    image: cypress/included:13.15.1
    volumes:
      - ./demo:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /e2e
    environment:
      CYPRESS_DEMO_URL: http://demo:5173
      CYPRESS_INBUCKET_URL: http://inbucket:9000
      CYPRESS_PB_URL: http://pocketbase
      DISPLAY: $DISPLAY
    entrypoint: "cypress"
    command: ["open", "--project", "."]
    depends_on:
      demo:
        condition: service_healthy
      pocketbase:
        condition: service_healthy
