name: E2E Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker compose up
      run: |
        docker-compose up -d demo pocketbasee inbucket
    
    - name: Run Cypress tests
      run: |
        docker-compose up cypress
